# -*- coding: utf-8 -*-
#%% [markdown]
"""EEG+Mamba_Transformer_SSL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9zqxmWYhnMETHfJMAExgn7YuJTWWqnV

## EEG **MAMBA**
"""

#%%
# Pure PyTorch Mamba is implemented below to avoid heavy wheel-compilation issues.
# No need to install causal-conv1d or mamba-ssm!

#%%
# ==============================
# 📦 IMPORTS
# ==============================
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc
from google.colab import drive

drive.mount('/content/drive')

import math
import torch.nn.functional as F

# Pure PyTorch Mamba Block (Drop-in replacement for mamba_ssm.Mamba)
class Mamba(nn.Module):
    def __init__(self, d_model, d_state=16, d_conv=4, expand=2):
        super().__init__()
        self.d_model = d_model
        self.d_state = d_state
        self.d_conv = d_conv
        self.expand = expand
        self.d_inner = d_model * expand
        self.dt_rank = math.ceil(self.d_model / 16)
        
        # Input projection
        self.in_proj = nn.Linear(self.d_model, self.d_inner * 2, bias=False)
        
        # Causal Convolution
        self.conv1d = nn.Conv1d(
            in_channels=self.d_inner,
            out_channels=self.d_inner,
            kernel_size=self.d_conv,
            bias=True,
            groups=self.d_inner,
            padding=self.d_conv - 1
        )
        
        # x projection to dt, B, C
        self.x_proj = nn.Linear(self.d_inner, self.dt_rank + self.d_state * 2, bias=False)
        
        # dt projection
        self.dt_proj = nn.Linear(self.dt_rank, self.d_inner, bias=True)
        
        # SSM parameters
        # S4D initialization for A
        A = torch.arange(1, self.d_state + 1, dtype=torch.float32).repeat(self.d_inner, 1)
        self.A_log = nn.Parameter(torch.log(A))
        
        # D parameter (skip connection)
        self.D = nn.Parameter(torch.ones(self.d_inner))
        
        # Output projection
        self.out_proj = nn.Linear(self.d_inner, self.d_model, bias=False)

    def forward(self, x):
        # x: (B, L, d_model)
        B, L, _ = x.shape
        
        # Projection to x and z branches
        projected = self.in_proj(x)  # (B, L, d_inner * 2)
        x, z = projected.chunk(2, dim=-1)  # (B, L, d_inner), (B, L, d_inner)
        
        # Causal Conv1D
        x = x.transpose(-1, -2)  # (B, d_inner, L)
        x = self.conv1d(x)[:, :, :L]  # Causal convolution, keep length L
        x = x.transpose(-1, -2)  # (B, L, d_inner)
        
        x = F.silu(x)
        
        # Project x to dt, B, C
        x_dbl = self.x_proj(x)  # (B, L, dt_rank + d_state * 2)
        dt, B_ssm, C_ssm = torch.split(x_dbl, [self.dt_rank, self.d_state, self.d_state], dim=-1)
        
        # Discretize dt
        dt = F.softplus(self.dt_proj(dt))  # (B, L, d_inner)
        
        # Reconstruct A
        A = -torch.exp(self.A_log.float())  # (d_inner, d_state)
        
        # SSM Scan
        h = torch.zeros(B, self.d_inner, self.d_state, device=x.device, dtype=x.dtype)
        ys = []
        for l in range(L):
            dt_l = dt[:, l, :].unsqueeze(-1)  # (B, d_inner, 1)
            B_l = B_ssm[:, l, :].unsqueeze(1)    # (B, 1, d_state)
            C_l = C_ssm[:, l, :].unsqueeze(1)    # (B, 1, d_state)
            x_l = x[:, l, :].unsqueeze(-1)    # (B, d_inner, 1)
            
            # Discretize A and B
            dA = torch.exp(dt_l * A.unsqueeze(0))  # (B, d_inner, d_state)
            dB = dt_l @ B_l  # (B, d_inner, d_state)
            
            # State update
            h = dA * h + dB * x_l
            
            # Output step
            y_l = (h @ C_l.transpose(-1, -2)).squeeze(-1)  # (B, d_inner)
            ys.append(y_l)
            
        y = torch.stack(ys, dim=1)  # (B, L, d_inner)
        
        # Residual connection
        y = y + x * self.D.unsqueeze(0).unsqueeze(0)
        
        # Gate and out projection
        y = y * F.silu(z)
        return self.out_proj(y)

# ==============================
# ⚙️ SETTINGS
# ==============================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

root_dir = "/content/drive/MyDrive/AUTISM_2026/dataset"
window_size = 256

# ==============================
# 📦 DATASET
# ==============================
class EEGDataset(Dataset):
    def __init__(self, root_dir):
        self.data = []
        self.labels = []

        class_map = {"ASD":1, "TD":0}

        print("📂 Loading dataset...")

        for cls, label in class_map.items():
            path = os.path.join(root_dir, cls)

            if not os.path.exists(path):
                print(f"❌ Missing: {path}")
                continue

            for file in os.listdir(path):
                if not file.endswith(".csv"): continue

                df = pd.read_csv(os.path.join(path,file))

                if 'subject' not in df.columns:
                    continue

                data = df.drop(columns=['subject','event']).values

                n = len(data)//window_size
                if n == 0:
                    continue

                data = data[:n*window_size]
                data = data.reshape(n,window_size,-1)
                data = np.transpose(data,(0,2,1))  # (N,64,256)

                for seg in data:
                    self.data.append(seg)
                    self.labels.append(label)

        if len(self.data) == 0:
            raise ValueError("❌ No data found")

        self.data = np.array(self.data)
        self.labels = np.array(self.labels)

        print(f"✅ Total samples: {len(self.data)}")

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        x = self.data[idx]
        x = (x - np.mean(x)) / (np.std(x) + 1e-6)

        return torch.tensor(x, dtype=torch.float32), \
               torch.tensor(self.labels[idx], dtype=torch.long)

# ==============================
# 🧠 REAL MAMBA MODEL
# ==============================
class EEGMamba(nn.Module):
    def __init__(self, d_model=64):
        super().__init__()

        self.input_proj = nn.Linear(64, d_model)

        self.mamba = Mamba(
            d_model=d_model,
            d_state=16,
            d_conv=4,
            expand=2
        )

        self.norm = nn.LayerNorm(d_model)
        self.fc = nn.Linear(d_model, 2)

    def forward(self, x):
        # (B,64,256) → (B,256,64)
        x = x.permute(0,2,1)

        x = self.input_proj(x)

        x = self.mamba(x)

        x = self.norm(x)

        x = x.mean(dim=1)

        return self.fc(x)

# ==============================
# 🚀 LOAD DATA
# ==============================
dataset = EEGDataset(root_dir)

train_size = int(0.8*len(dataset))
test_size = len(dataset)-train_size

train_ds, test_ds = random_split(dataset,[train_size,test_size])

train_loader = DataLoader(train_ds,32,True)
test_loader = DataLoader(test_ds,32,False)

print(f"Train samples: {len(train_ds)}")
print(f"Test samples: {len(test_ds)}")

# ==============================
# 🚀 MODEL
# ==============================
model = EEGMamba().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

train_acc_list=[]
test_acc_list=[]

# ==============================
# 🚀 TRAINING
# ==============================
for epoch in range(50):

    # TRAIN
    model.train()
    correct,total=0,0

    for x,y in train_loader:
        x,y = x.to(device),y.to(device)

        out = model(x)
        loss = criterion(out,y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        pred = out.argmax(1)
        correct += (pred==y).sum().item()
        total += y.size(0)

    train_acc = 100*correct/total

    # TEST
    model.eval()
    correct,total=0,0

    all_preds=[]
    all_labels=[]
    all_probs=[]

    with torch.no_grad():
        for x,y in test_loader:
            x,y = x.to(device),y.to(device)

            out = model(x)
            probs = torch.softmax(out,1)[:,1]
            pred = out.argmax(1)

            correct += (pred==y).sum().item()
            total += y.size(0)

            all_preds.extend(pred.cpu().numpy())
            all_labels.extend(y.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    test_acc = 100*correct/total

    train_acc_list.append(train_acc)
    test_acc_list.append(test_acc)

    print(f"Epoch {epoch+1} | Train: {train_acc:.2f}% | Test: {test_acc:.2f}%")

# ==============================
# 📊 ACCURACY GRAPH
# ==============================
plt.plot(train_acc_list,label="Train")
plt.plot(test_acc_list,label="Test")
plt.legend()
plt.title("Accuracy")
plt.show()

# ==============================
# 📊 CONFUSION MATRIX
# ==============================
cm = confusion_matrix(all_labels,all_preds)
ConfusionMatrixDisplay(cm,display_labels=["TD","ASD"]).plot()
plt.show()

# ==============================
# 📈 ROC CURVE
# ==============================
fpr,tpr,_ = roc_curve(all_labels,all_probs)
roc_auc = auc(fpr,tpr)

plt.plot(fpr,tpr,label=f"AUC={roc_auc:.3f}")
plt.plot([0,1],[0,1],'--')
plt.legend()
plt.title("ROC Curve")
plt.show()

#%% [markdown]
"""TRANSFORMER **ONLY**"""

#%%
# ==============================
# 📦 IMPORTS
# ==============================
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc
from google.colab import drive
drive.mount('/content/drive')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

root_dir = "/content/drive/MyDrive/AUTISM_2026/dataset"
window_size = 256

# ==============================
# 📦 DATASET
# ==============================
class EEGDataset(Dataset):
    def __init__(self, root_dir):
        self.data = []
        self.labels = []

        class_map = {"ASD":1, "TD":0}

        print("📂 Loading dataset...")

        for cls, label in class_map.items():
            path = os.path.join(root_dir, cls)

            if not os.path.exists(path):
                print(f"❌ Missing: {path}")
                continue

            for file in os.listdir(path):
                if not file.endswith(".csv"): continue

                df = pd.read_csv(os.path.join(path,file))

                if 'subject' not in df.columns:
                    continue

                data = df.drop(columns=['subject','event']).values

                n = len(data)//window_size
                if n == 0:
                    continue

                data = data[:n*window_size]
                data = data.reshape(n,window_size,-1)
                data = np.transpose(data,(0,2,1))  # (N,64,256)

                for seg in data:
                    self.data.append(seg)
                    self.labels.append(label)

        if len(self.data) == 0:
            raise ValueError("❌ No data found")

        self.data = np.array(self.data)
        self.labels = np.array(self.labels)

        print(f"✅ Total samples: {len(self.data)}")

    def __len__(self): return len(self.data)

    def __getitem__(self, idx):
        x = self.data[idx]

        # Normalization
        x = (x - np.mean(x)) / (np.std(x) + 1e-6)

        return torch.tensor(x, dtype=torch.float32), \
               torch.tensor(self.labels[idx], dtype=torch.long)

# ==============================
# 🧠 TRANSFORMER MODEL
# ==============================
class EEGTransformer(nn.Module):
    def __init__(self, d_model=64, nhead=4, num_layers=3):
        super().__init__()

        self.input_proj = nn.Linear(64, d_model)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dropout=0.2,
            batch_first=True
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        self.norm = nn.LayerNorm(d_model)

        self.fc = nn.Linear(d_model, 2)

    def forward(self, x):
        # x: (B,64,256)
        x = x.permute(0,2,1)  # (B,256,64)

        x = self.input_proj(x)
        x = self.transformer(x)
        x = self.norm(x)

        x = x.mean(dim=1)  # global pooling

        return self.fc(x)

# ==============================
# 🚀 LOAD DATA
# ==============================
dataset = EEGDataset(root_dir)

train_size = int(0.8*len(dataset))
test_size = len(dataset)-train_size

train_ds, test_ds = random_split(dataset,[train_size,test_size])

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
test_loader = DataLoader(test_ds, batch_size=32, shuffle=False)

# ==============================
# 🚀 MODEL SETUP
# ==============================
model = EEGTransformer().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

# ==============================
# 🚀 TRAINING
# ==============================
train_acc_list = []
test_acc_list = []

epochs = 50

for epoch in range(epochs):

    # -------- TRAIN --------
    model.train()
    correct,total = 0,0

    for x,y in train_loader:
        x,y = x.to(device),y.to(device)

        out = model(x)
        loss = criterion(out,y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        pred = out.argmax(1)
        correct += (pred==y).sum().item()
        total += y.size(0)

    train_acc = 100*correct/total

    # -------- TEST --------
    model.eval()
    correct,total = 0,0

    all_preds=[]
    all_labels=[]
    all_probs=[]

    with torch.no_grad():
        for x,y in test_loader:
            x,y = x.to(device),y.to(device)

            out = model(x)
            probs = torch.softmax(out,1)[:,1]
            pred = out.argmax(1)

            correct += (pred==y).sum().item()
            total += y.size(0)

            all_preds.extend(pred.cpu().numpy())
            all_labels.extend(y.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())

    test_acc = 100*correct/total

    train_acc_list.append(train_acc)
    test_acc_list.append(test_acc)

    print(f"Epoch {epoch+1} | Train: {train_acc:.2f}% | Test: {test_acc:.2f}%")

# ==============================
# 📊 ACCURACY GRAPH
# ==============================
plt.plot(train_acc_list,label="Train")
plt.plot(test_acc_list,label="Test")
plt.legend()
plt.title("Accuracy")
plt.show()

# ==============================
# 📊 CONFUSION MATRIX
# ==============================
cm = confusion_matrix(all_labels,all_preds)
ConfusionMatrixDisplay(cm,display_labels=["TD","ASD"]).plot()
plt.show()

# ==============================
# 📈 ROC CURVE
# ==============================
fpr,tpr,_ = roc_curve(all_labels,all_probs)
roc_auc = auc(fpr,tpr)

plt.plot(fpr,tpr,label=f"AUC={roc_auc:.3f}")
plt.plot([0,1],[0,1],'--')
plt.legend()
plt.title("ROC Curve")
plt.show()